sudo: required
dist: xenial
services: [docker]
language: c
env:
  - TEST_SUITE=release
  - TEST_SUITE=asan
  - TEST_SUITE=ubsan
  - TEST_SUITE=release:gnu
install:
  - docker pull gregjm/cpp-build
  - docker build --privileged --tag bloodhound .
script: docker run --rm bloodhound "${TEST_SUITE}"
